### ISSUE TITLE
Nedaří se mi sestavit kontejner

### ISSUE THREAD

**Issue by lukaskett** [paukert/kuoris-v2#4]
Při postupu dle návodu příkaz `docker-compose` mi hlásil systém že nenalezen, tak jsem použil `docker compose` a vrací se mi chyba:
```log
128.0 ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
------
failed to solve: process "/bin/sh -c set -eux; \tapk add --no-cache --virtual .build-deps \t\t$PHPIZE_DEPS \t\ticu-dev \t\tlibzip-dev \t\tzlib-dev \t; \t\tdocker-php-ext-configure zip; \tdocker-php-ext-install -j$(nproc) \t\tintl \t\tzip \t\tmysqli \t\tpdo \t\tpdo_mysql \t; \tpecl install \t\tapcu-${APCU_VERSION} \t\txdebug \t; \tpecl clear-cache; \tdocker-php-ext-enable \t\tapcu \t\topcache \t\txdebug \t; \t\trunDeps=\"$( \t\tscanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \t\t\t| tr ',' '\\n' \t\t\t| sort -u \t\t\t| awk 'system(\"[ -e /usr/local/lib/\" $1 \" ]\") == 0 { next } { print \"so:\" $1 }' \t)\"; \tapk add --no-cache --virtual .phpexts-rundeps $runDeps; \t\tapk del .build-deps" did not complete successfully: exit code: 1
```
Verze `dockeru`
![image](https://github.com/paukert/kuoris-v2/assets/29544822/6ece846e-ad99-4132-8386-64ddf1512237)

Zkoušel jsem na OS: `CentOS Stream release 8`.

Nemám nainstalované php a ještě spouštím se `sudo`, tak nevím jestli něco z toho nemůže dělat problémy.

**Comment by paukert** [comment]
Omlouvám se za pozdější reakci, mělo by to být opraveno (viz https://github.com/paukert/kuoris-v2/commit/d17ad1f9ed71a8b8c2b1228ff9cfdecabf6eb759), prosím o vyzkoušení.

**Comment by lukaskett** [comment]
Ahoj, tak jsem na to teď koukal a podařilo se mi nějak základně rozchodit (přihlásil jsem se na výchozích uživatele, zaregistroval nového uživatele a na něj se taky přihlásil) a pro představu jak funguje mi stačí, díky.
Celkově to má nějak pomalé odezvy na to, že mám spuštěno z lokálu.

**Comment by paukert** [comment]
Důvodů pro delší odezvu může být více:
- malé zdroje pro docker,
- běh aplikace s debug nástroji (při spuštění způsobem popsaným v repozitáři se aplikace spouští v debug módu)
- a asi i další důvody, které mě nyní nenapadly.

Těžko říci, co bude přesnou příčinou u tebe.
