### ISSUE TITLE
Instalace závislostí

### ISSUE THREAD

**Issue by lukaskett** [paukert/kuoris-v2#5]
Příkaz `docker-compose exec php php composer install` mi končí chybou:

```
service "php" is not running
```

asi vyžaduje ještě další závislosti co nemám.

**Comment by paukert** [comment]
Tahle chybová hláška říká, že container s aplikací neběží - container se jmenuje `php` viz https://github.com/paukert/kuoris-v2/blob/9b24446a2ad5ea35d889e30a66bd9bf010a846fd/docker-compose.yml#L4

Bude to souviset s tím, že se ti nepovedlo sestavit samotný container, takže v něm není ani možné spouštět příkazy. Po vyřešení https://github.com/paukert/kuoris-v2/issues/4 by neměl být problém tento příkaz spustit.
